services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8080
    volumes:
      - .:/app
    env_file:
      - .env
    mem_limit: 2g
  pusher:
    build:
      context: .
      dockerfile: pusher.Dockerfile
    ports:
      - 8098:8080
    volumes:
      - .:/app
    env_file:
      - .env
    mem_limit: 1g
  vad:
    build:
      context: .
      dockerfile: vad.Dockerfile
    mem_limit: 3g
    ports:
      - 8188:8080
    env_file:
      - .env
  plugins:
    build:
      context: ../plugins/example
      dockerfile: Dockerfile
    ports:
      - 8189:8000
    volumes:
      - ../plugins/example:/app
    env_file:
      - ../plugins/example/.env
    mem_limit: 512m
