name: omi
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.519+570

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  connectivity_plus: ^6.0.3
  flutter_provider_utilities: ^1.0.6

  # Desktop
  window_manager: 0.3.7
  auto_updater: ^1.0.0

  # Localizations
  flutter_localizations:
    sdk: flutter

  # UI
  auto_size_text: 3.0.0
  lottie: ^3.1.2
  expandable_text: ^2.3.0
  flutter_native_splash: ^2.4.0
  gradient_borders: ^1.0.1
  visibility_detector: ^0.4.0+2
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  skeletonizer: 2.0.1
  shimmer: ^3.0.0
  pull_down_button: ^0.10.2

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Firebase
  firebase_core: 3.13.0
  firebase_auth: 5.5.3
  firebase_messaging: 15.2.5
  firebase_crashlytics: 4.3.2

  # Auth
  google_sign_in: 6.2.2
  sign_in_with_apple: ^6.1.1

  # Analytics and Support
  intercom_flutter: 9.4.22
  mixpanel_flutter:
    git:
      url: https://github.com/beastoin/mixpanel-flutter.git
      ref: f9234e9
  mixpanel_analytics:
    git:
      url: https://github.com/mdmohsin7/mixpanel_analytics.git
      ref: master

  # Logging
  talker_flutter: 5.0.0

  # Devices
  frame_sdk:
    git:
      url: https://github.com/mdmohsin7/frame-sdk-flutter.git
      ref: master

  # Utils
  pool: ^1.5.1
  collection: ^1.19.1
  flutter_blue_plus: 2.1.0
  http: ^1.4.0
  pdf: ^3.11.0
  intl: 0.20.2
  permission_handler: ^12.0.0+1
  flutter_contacts: ^1.1.9+2
  share_plus: 11.0.0
  shared_preferences: 2.5.3
  url_launcher: ^6.3.0
  wav: ^1.4.0
  path: ^1.9.0
  uuid: ^4.4.0
  tuple: ^2.0.2
  googleapis_auth: 2.0.0
  envied: 1.1.1
  awesome_notifications_core: ^0.9.3
  awesome_notifications: any
  nordic_dfu: ^6.1.4+hotfix
  mcumgr_flutter: ^0.4.2
  flutter_archive: ^6.0.3
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  package_info_plus: ^8.0.1
  device_info_plus: ^11.5.0
  path_provider: 2.1.5
  flutter_foreground_task: 9.1.0
  upgrader: 11.4.0
  crypto: ^3.0.3
  flutter_markdown: ^0.7.7
  flutter_background_service: 5.1.0
  flutter_background_service_android: 6.3.0
  flutter_background_service_platform_interface: 5.1.2
  opus_flutter: ^3.0.3
  opus_dart:
    git:
      url: https://github.com/mdmohsin7/opus_dart.git
      ref: dev
  growthbook_sdk_flutter: 3.9.2
  flutter_timezone: 3.0.1
  cached_network_image: 3.4.1
  map_launcher: ^3.5.0
  internet_connection_checker_plus: ^2.7.2
  geolocator: 14.0.1
  version: ^3.0.2
  webview_flutter: 4.13.0
  flutter_sound: 9.25.1
  just_audio: ^0.9.39
  video_player: ^2.8.2
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  timeago: ^3.7.0
  app_links: ^6.3.2
  flutter_svg: ^2.0.16
  file_picker: 8.3.2
  photo_view: ^0.15.0
  font_awesome_flutter: ^10.8.0
  in_app_review: ^2.0.9
  fl_chart: ^0.68.0
  image: ^4.3.0
  calendar_date_picker2: ^2.0.1
  whisper_flutter_new: ^1.0.1
  disk_space_2: ^1.0.11

dependency_overrides:
  js: ^0.7.1
  uuid: ^4.4.0
  flutter_blue_plus: 2.1.0
  opus_flutter_ios:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_ios
      ref: dev
  opus_flutter_android:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_android

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  google_sign_in_ios: 5.7.5
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
  envied_generator: 1.1.1
  build_runner: ^2.4.15
  flutter_flavorizr: ^2.2.3
  flutter_gen_runner: 5.10.0
  pigeon: ^26.0.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/stars.png
    - assets/images/herologo.png
    - assets/fonts/
    - assets/images/
    - assets/integration_app_logos/
    - assets/competitor-logos/
    - shorebird.yaml
    - assets/device_assets/frame_lib.lua
  fonts:
    - family: "SF Pro Display"
      fonts:
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic

flutter_gen:
  output: lib/gen/

flutter_native_splash:
  background_image: "assets/images/splash.png"
  android_12:
    image: assets/images/splash_icon.png
    color: "#000000" # TODO: improve hero banner on android12

  android: true
  ios: true
