name: friend_private
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.39+138

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.2
  flutter_provider_utilities: ^1.0.6

  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  auto_size_text: 3.0.0
  collection: 1.18.0
  equatable: 2.0.5
  flutter_blue_plus: ^1.32.12
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: 1.1.0
  url_launcher: ^6.3.0
  url_launcher_platform_interface: 2.3.2
  wav: ^1.3.0
  lottie: ^3.1.2
  flutter_tilt: any
  path: ^1.9.0
  uuid: ^4.4.0
  tuple: ^2.0.2
  googleapis_auth: ^1.6.0
  envied: ^0.5.4+1
  awesome_notifications_core: ^0.9.3
  awesome_notifications: any
  mime: ^1.0.5
  instabug_flutter: ^13.3.0
  instabug_http_client: ^2.4.0
  mixpanel_flutter: ^2.2.0
  expandable_text: ^2.3.0
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  nordic_dfu: ^6.1.4+hotfix
  package_info_plus: ^8.0.1

  path_provider: any
  flutter_foreground_task: 8.2.0
  deepgram_speech_to_text: ^2.1.1
  upgrader: ^10.3.0
  crypto: ^3.0.3
  flutter_markdown: ^0.7.2+1
  file_picker: ^8.0.5
  flutter_background_service: ^5.0.7
  flutter_background_service_android: 6.2.4
  flutter_background_service_platform_interface: 5.1.1
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1
  growthbook_sdk_flutter: ^3.9.2
  flutter_rating_bar: ^4.0.1
  manage_calendar_events: ^2.0.3
  flutter_timezone: ^2.0.0
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.1
  firebase_core: 3.3.0
  firebase_auth: 5.1.4
  google_sign_in: ^6.2.1
  location: ^7.0.0
  cached_network_image: ^3.3.1
  map_launcher: ^3.3.1
  internet_connection_checker_plus: ^2.5.0
  geolocator:
  visibility_detector: ^0.4.0+2
  firebase_messaging: 15.0.4
  version: ^3.0.2
  webview_flutter: ^4.8.0
  flutter_sound: ^9.10.0
  just_audio: ^0.9.39
  frame_sdk: ^0.0.7
  gleap_sdk: ^13.9.1
  web_socket_channel: ^3.0.1
  talker_flutter:

  intercom_flutter:


dependency_overrides:
  http: ^1.2.1
  uuid: ^4.4.0
  js: ^0.7.1
  opus_flutter_android:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_android
  # flutter_blue_plus:
    # git:
    #   url: https://github.com/chipweinberger/flutter_blue_plus
    #   ref: 1.32.13
    #   version: ^1.32.13
  manage_calendar_events:
    git:
       url: https://github.com/beastoin/manage_calendar_events
       ref: master
       version: ^2.0.4


dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^4.0.0
  image: ^4.2.0
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
  flutter_flavorizr: ^2.2.3


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


flutter:
  uses-material-design: true
  assets:
    - assets/images/blob.png
    - assets/images/stars.png
    - assets/images/herologo.png
    - assets/images/backbutton.svg
    - assets/fonts/
    - assets/images/
    - assets/lottie_animations/
    - assets/pdfs/
    - assets/silero_vad.onnx
    - shorebird.yaml
    - assets/device_assets/frame_lib.lua
  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic

flutter_native_splash:
  background_image: "assets/images/splash.png"
  android_12:
    image: assets/images/splash_icon.png
    color: "#000000" # TODO: improve hero banner on android12

  android: true
  ios: true

