apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: deepgram-backend-config
spec:
  timeoutSec: 999999999  # Set to a high value to disable the timeout
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    port: {{ .Values.api.server.port }}
    type: HTTP
    requestPath: /v1/status/engine  # Ensure this path returns 200 OK
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.namePrefix }}-external
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    app: deepgram-api
    {{- range $key, $val := .Values.api.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "deepgram-backend-config"}'  # Link to BackendConfig
spec:
  selector:
    app: deepgram-api
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.api.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: "primary"
      port: {{ .Values.api.server.port }}
      targetPort: {{ .Values.api.server.port }}

