{{- $engineTypes := list }}
{{- if .Values.agent.enabled }}
{{- $engineTypes = list "agent-speech-to-text" "agent-text-to-speech" "agent-end-of-turn" }}
{{- else }}
{{- $engineTypes = list "" }}
{{- end }}
{{- range $type := $engineTypes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.engine.namePrefix }}{{- if $type }}-{{ $type }}{{- end }}-metrics
  labels:
{{ include "deepgram-self-hosted.labels" $ | indent 4}}
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{- range $key, $val := $.Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- if and (eq $.Values.engine.service.type "LoadBalancer") $.Values.engine.service.annotations }}
  annotations:
    {{- range $key, $val := $.Values.engine.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- end }}
spec:
  selector:
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{ include "deepgram-self-hosted.selectorLabels" $ }}
  type: {{ $.Values.engine.service.type | default "ClusterIP" }}
  {{- if and (eq $.Values.engine.service.type "LoadBalancer") $.Values.engine.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $.Values.engine.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq $.Values.engine.service.type "LoadBalancer") $.Values.engine.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $.Values.engine.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: "metrics"
      port: {{ $.Values.engine.metricsServer.port }}
      targetPort: {{ $.Values.engine.metricsServer.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.engine.namePrefix }}{{- if $type }}-{{ $type }}{{- end }}-internal
  labels:
{{ include "deepgram-self-hosted.labels" $ | indent 4}}
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{- range $key, $val := $.Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{ include "deepgram-self-hosted.selectorLabels" $ }}
  type: ClusterIP
  ports:
    - name: "primary"
      port: {{ $.Values.engine.server.port }}
      targetPort: {{ $.Values.engine.server.port }}
{{- end }}
