# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github
have_fun: false
code_review:
  comment_severity_threshold: HIGH
  pull_request_opened:
    help: false
    summary: false
    code_review: true
    include_drafts: true
ignore_patterns: []

review_preferences:
  minimum_severity: "high"
  include_code_suggestions: true
  focus_areas:
    - "correctness"
    - "security"
  # style_guide_path: ".gemini/my_custom_style_guide.md"
