title: Friend
description: Open Source AI Wearable device
theme: just-the-docs
url: https://basedhardware.github.io
logo: "/images/logo.png"
favicon_ico: "/images/favicon.ico"

collections:
  get_started:
    permalink: "/:collection/:path/"
    output: true
  assembly:
    permalink: "/:collection/:path/"
    output: true
  info:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    get_started:
      name: Get Started
    assembly:
      name: Assembly
    info:
      name: Info

callouts:
  warning:
    title: Warning
    color: yellow
  error:
    title: Alert
    color: red
  note:
    title: Note
    color: blue

aux_links:
  Github: https://github.com/BasedHardware/Friend

aux_links_new_tab: true

nav_external_links:
  - title: ğŸ’¬ | Discord
    url: https://discord.gg/kEXXsnb5b3
    opens_in_new_tab: true

  - title: ğŸ§‘â€ğŸ’» | GitHub
    url: https://github.com/BasedHardware/Friend
    opens_in_new_tab: true
