name: Deploy Apps-Js to Cloud RUN

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - 'plugins/apps-js/**'

env:
  SERVICE: apps-js
  REGION: us-central1

jobs:
  deploy:
    environment: ${{ (github.ref == 'refs/heads/development' && 'development') || (github.ref == 'refs/heads/main' && 'prod') }}
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            --build-arg UPSTASH_REDIS_HOST=${{ secrets.UPSTASH_REDIS_HOST }} \
            --build-arg UPSTASH_REDIS_PASSWORD=${{ secrets.UPSTASH_REDIS_PASSWORD }} \
            --build-arg UPSTASH_REDIS_PORT=${{ secrets.UPSTASH_REDIS_PORT }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} \
            --build-arg GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }} \
            --build-arg BASE_URL=${{ secrets.BASE_URL }} \
            --build-arg SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --build-arg SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --build-arg OMI_APP_ID=${{ secrets.OMI_APP_ID }} \
            --build-arg OMI_APP_SECRET=${{ secrets.OMI_APP_SECRET }} \
            --build-arg DECK_APP_ID=${{ secrets.DECK_APP_ID }} \
            --build-arg DECK_APP_SECRET=${{ secrets.DECK_APP_SECRET }} \
            --build-arg SLIDESGPT_API_KEY=${{ secrets.SLIDESGPT_API_KEY }} \
            -t gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }} -f plugins/apps-js/Dockerfile.datadog .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}